'use client'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import AppShell from '../../components/AppShell'
import PageHeader from '../../components/PageHeader'
import StatusBadge from '../../components/StatusBadge'
import { getPackCoverage, getDocuments, getWorkers, getCertifications } from '../../lib/mockStore'

export default function PacksPage() {
  const [coverage, setCoverage] = useState([])
  const [filter, setFilter] = useState('all')
  const [selectedWorker, setSelectedWorker] = useState(null)
  const [workerDocs, setWorkerDocs] = useState([])
  const [workerCerts, setWorkerCerts] = useState([])
  const [selectedDocIds, setSelectedDocIds] = useState([])
  const [building, setBuilding] = useState(false)

  useEffect(() => {
    setCoverage(getPackCoverage())
  }, [])

  const openPackBuilder = (workerId) => {
    const workers = getWorkers()
    const worker = workers.find(w => w.id === workerId)
    const docs = getDocuments().filter(d => d.worker_id === workerId)
    const certs = getCertifications().filter(c => c.worker_id === workerId)
    setSelectedWorker(worker)
    setWorkerDocs(docs)
    setWorkerCerts(certs)
    setSelectedDocIds([])
  }

  const toggleDoc = (id) => {
    setSelectedDocIds(prev => prev.includes(id) ? prev.filter(x=>x!==id) : [...prev,id])
  }

  const handleBuildZip = async () => {
    if (selectedDocIds.length === 0) return
    setBuilding(true)
    try {
      const JSZip = (await import('jszip')).default
      const zip = new JSZip()
      const folder = zip.folder(`${selectedWorker.worker_number}_${selectedWorker.full_name.replace(/\s+/g,'_')}_Pack`)

      const allItems = [
        ...workerDocs.map(d => ({id:d.id, name: d.file_name || `${selectedWorker.worker_number}_${selectedWorker.full_name.replace(/\s+/g,'_')}_${d.document_type}.pdf`, type:'document', item:d})),
        ...workerCerts.map(c => ({id:c.id, name: c.file_name || `${selectedWorker.worker_number}_${selectedWorker.full_name.replace(/\s+/g,'_')}_${c.certification_type.replace(/\s+/g,'_')}.pdf`, type:'cert', item:c}))
      ]

      const selected = allItems.filter(i => selectedDocIds.includes(i.id))

      selected.forEach(item => {
        const mockContent = `[MOCK FILE - ${item.type.toUpperCase()}]\n\nWorker: ${selectedWorker.full_name}\nID: ${selectedWorker.worker_number}\nDocument: ${item.name}\n\nThis is a placeholder. Real file upload integration required.\nGenerated: ${new Date().toISOString()}`
        folder.file(item.name, mockContent)
      })

      const manifest = `WORKER PACK MANIFEST\n${'='.repeat(40)}\nWorker: ${selectedWorker.full_name}\nID: ${selectedWorker.worker_number}\nPack generated: ${new Date().toLocaleString()}\nGenerated by: Innovation Technologies LLC O.P.C.\n\nDOCUMENTS INCLUDED (${selected.length}):\n${selected.map((s,i)=>`${i+1}. ${s.name}`).join('\n')}\n`
      folder.file('_PACK_MANIFEST.txt', manifest)

      const blob = await zip.generateAsync({type:'blob'})
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${selectedWorker.worker_number}_${selectedWorker.full_name.replace(/\s+/g,'_')}_Pack.zip`
      a.click()
      URL.revokeObjectURL(url)
    } catch(e) {
      console.error('ZIP error:', e)
    }
    setBuilding(false)
  }

  const filtered = filter==='all' ? coverage : filter==='ready' ? coverage.filter(p=>p.available_count===p.required_count) : coverage.filter(p=>p.available_count<p.required_count)
  const ready = coverage.filter(p=>p.available_count===p.required_count).length
  const blocked = coverage.filter(p=>p.available_count<p.required_count).length
  const totalMissing = coverage.reduce((s,p)=>s+(p.required_count-p.available_count),0)

  return (
    <AppShell pageTitle="Packs">
      <PageHeader eyebrow="Packs" title="Pack builder" description="Select documents for each worker and download as a ZIP pack for client submission." />
      <div className="summary-strip">
        <div className="stat-card"><div className="num success" style={{fontSize:20}}>{ready}</div><div className="lbl">Pack ready</div></div>
        <div className="stat-card"><div className="num danger" style={{fontSize:20}}>{blocked}</div><div className="lbl">Blocked</div></div>
        <div className="stat-card"><div className="num warning" style={{fontSize:20}}>{totalMissing}</div><div className="lbl">Missing items</div></div>
        <div className="stat-card"><div className="num" style={{fontSize:20}}>{coverage.length}</div><div className="lbl">Workers assessed</div></div>
      </div>

      <div style={{display:'grid',gridTemplateColumns: selectedWorker ? '1fr 380px' : '1fr',gap:16}}>
        <div className="panel">
          <div className="toolbar">
            {[['all','All'],['ready','Ready'],['blocked','Blocked']].map(([key,label])=>(
              <button key={key} className={`btn btn-sm ${filter===key?'btn-teal':'btn-secondary'}`} onClick={()=>setFilter(key)}>{label}</button>
            ))}
          </div>
          <div className="table-wrap">
            <table>
              <thead><tr><th>Worker</th><th>Category</th><th>Status</th><th>Coverage</th><th>Missing</th><th>Build Pack</th></tr></thead>
              <tbody>
                {filtered.map(p=>(
                  <tr key={p.worker_id} style={{background:selectedWorker?.id===p.worker_id?'#f0fdfa':''}}>
                    <td style={{fontWeight:500}}>{p.worker_name}<div style={{fontSize:11,color:'var(--hint)'}}>{p.worker_number}</div></td>
                    <td><StatusBadge label={p.category} tone="neutral" /></td>
                    <td><StatusBadge label={p.available_count===p.required_count?'Ready':'Blocked'} tone={p.available_count===p.required_count?'success':'danger'} /></td>
                    <td><div style={{display:'flex',alignItems:'center',gap:8}}><div style={{flex:1,height:4,background:'var(--border)',borderRadius:2}}><div style={{width:`${Math.min((p.available_count/p.required_count)*100,100)}%`,height:'100%',background:p.available_count===p.required_count?'var(--success)':'var(--warning)',borderRadius:2}}/></div><span style={{fontSize:11,color:'var(--muted)',whiteSpace:'nowrap'}}>{p.available_count}/{p.required_count}</span></div></td>
                    <td style={{fontSize:12,color:'var(--danger)'}}>{p.missing_types?.join(', ')||'—'}</td>
                    <td><button className="btn btn-teal btn-sm" onClick={()=>openPackBuilder(p.worker_id)}>📦 Select &amp; Build</button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {selectedWorker && (
          <div className="panel">
            <div className="panel-header">
              <div><h2>📦 {selectedWorker.full_name}</h2><p>{selectedWorker.worker_number} · {selectedWorker.category}</p></div>
              <button className="btn btn-ghost btn-sm" onClick={()=>setSelectedWorker(null)}>✕</button>
            </div>
            <div style={{fontSize:11,fontWeight:600,color:'var(--muted)',marginBottom:8}}>SELECT DOCUMENTS TO INCLUDE</div>

            {workerDocs.length > 0 && <>
              <div style={{fontSize:11,color:'var(--hint)',marginBottom:6,textTransform:'uppercase',letterSpacing:'0.5px'}}>Documents</div>
              {workerDocs.map(d=>(
                <label key={d.id} style={{display:'flex',alignItems:'center',gap:8,padding:'6px 0',borderBottom:'1px solid var(--border)',cursor:'pointer'}}>
                  <input type="checkbox" checked={selectedDocIds.includes(d.id)} onChange={()=>toggleDoc(d.id)} />
                  <div style={{flex:1}}>
                    <div style={{fontSize:12,fontWeight:500}}>{d.document_type}</div>
                    <div style={{fontSize:10,color:'var(--hint)'}}>{d.file_name||'No file uploaded'}</div>
                  </div>
                  <StatusBadge label={d.status} tone={d.status==='valid'?'success':d.status==='expired'?'danger':'warning'} />
                </label>
              ))}
            </>}

            {workerCerts.length > 0 && <>
              <div style={{fontSize:11,color:'var(--hint)',marginTop:12,marginBottom:6,textTransform:'uppercase',letterSpacing:'0.5px'}}>Certifications</div>
              {workerCerts.map(c=>(
                <label key={c.id} style={{display:'flex',alignItems:'center',gap:8,padding:'6px 0',borderBottom:'1px solid var(--border)',cursor:'pointer'}}>
                  <input type="checkbox" checked={selectedDocIds.includes(c.id)} onChange={()=>toggleDoc(c.id)} />
                  <div style={{flex:1}}>
                    <div style={{fontSize:12,fontWeight:500}}>{c.certification_type}</div>
                    <div style={{fontSize:10,color:'var(--hint)'}}>{c.file_name||'No file uploaded'}</div>
                  </div>
                  <StatusBadge label={c.status} tone={c.status==='valid'?'success':c.status==='expired'?'danger':'warning'} />
                </label>
              ))}
            </>}

            {workerDocs.length === 0 && workerCerts.length === 0 && (
              <div style={{color:'var(--hint)',fontSize:13,padding:'16px 0'}}>No documents or certifications on file for this worker.</div>
            )}

            <div style={{marginTop:16,paddingTop:12,borderTop:'1px solid var(--border)'}}>
              <div style={{fontSize:12,color:'var(--muted)',marginBottom:10}}>{selectedDocIds.length} item{selectedDocIds.length!==1?'s':''} selected</div>
              <button
                className="btn btn-primary"
                style={{width:'100%'}}
                disabled={selectedDocIds.length===0||building}
                onClick={handleBuildZip}
              >{building?'Building ZIP...':'⬇ Download Pack as ZIP'}</button>
              <button className="btn btn-ghost btn-sm" style={{width:'100%',marginTop:6}} onClick={()=>setSelectedDocIds(workerDocs.map(d=>d.id).concat(workerCerts.map(c=>c.id)))}>Select all</button>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  )
}
